@startuml
'https://plantuml.com/class-diagram
abstract plant{
blood
suncost
spawn()
destroyp()
attack()
}
abstract shootplant{
Bullet bullet
atk
}
class peashooter{
spawn()
destroyp()
attack()
}
plant<|--shootplant
shootplant<|--peashooter

@enduml